# Generated by Django 5.2 on 2026-03-22 17:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Role/Job Title', max_length=100)),
                ('department', models.CharField(blank=True, help_text='Department name', max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Role Matrices',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(blank=True, choices=[('technical', 'Technical'), ('soft', 'Soft Skills'), ('leadership', 'Leadership'), ('domain', 'Domain Knowledge'), ('tools', 'Tools & Software'), ('other', 'Other')], max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SkillMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave')], default='active', max_length=20)),
                ('join_date', models.DateField(blank=True, null=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='gap_analysis.skillmatrix')),
                ('role_matrix', models.ForeignKey(blank=True, help_text='Assigned Role', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gap_analysis.rolematrix')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeSkillHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_level', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('evaluated_on', models.DateTimeField(auto_now_add=True)),
                ('evaluated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gap_analysis.skill')),
                ('skill_matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_history', to='gap_analysis.skillmatrix')),
            ],
            options={
                'ordering': ['-evaluated_on'],
            },
        ),
        migrations.CreateModel(
            name='SkillBenchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_level', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('is_mandatory', models.BooleanField(default=True, help_text='Is this skill mandatory for the role?')),
                ('role_matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benchmarks', to='gap_analysis.rolematrix')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benchmarks', to='gap_analysis.skill')),
            ],
            options={
                'ordering': ['skill__name'],
                'unique_together': {('role_matrix', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_level', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('notes', models.TextField(blank=True, null=True)),
                ('last_evaluated', models.DateField(auto_now=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_skills', to='gap_analysis.skill')),
                ('skill_matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='gap_analysis.skillmatrix')),
            ],
            options={
                'ordering': ['skill__name'],
                'unique_together': {('skill_matrix', 'skill')},
            },
        ),
    ]
