# Generated by Django 6.0.3 on 2026-03-21 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gap_analysis.designation')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('actual_level', models.IntegerField(help_text='Scale of 1 to 5')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gap_analysis.employee')),
            ],
        ),
        migrations.CreateModel(
            name='SkillBenchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('required_level', models.IntegerField(help_text='Scale of 1 to 5')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gap_analysis.designation')),
            ],
        ),
    ]
