# Generated by Django 6.0.3 on 2026-03-21 10:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap_analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(blank=True, help_text='e.g., Technical, Soft Skill, Leadership', max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='designation',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employeeskill',
            name='last_evaluated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='employeeskill',
            name='actual_level',
            field=models.IntegerField(help_text='Scale of 1 to 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='skillbenchmark',
            name='required_level',
            field=models.IntegerField(help_text='Scale of 1 to 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='employeeskill',
            name='skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gap_analysis.skill'),
        ),
        migrations.AddField(
            model_name='skillbenchmark',
            name='skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gap_analysis.skill'),
        ),
        migrations.AlterUniqueTogether(
            name='employeeskill',
            unique_together={('employee', 'skill')},
        ),
        migrations.AlterUniqueTogether(
            name='skillbenchmark',
            unique_together={('designation', 'skill')},
        ),
        migrations.RemoveField(
            model_name='employeeskill',
            name='skill_name',
        ),
        migrations.RemoveField(
            model_name='skillbenchmark',
            name='skill_name',
        ),
    ]
