# Generated by Django 6.0.3 on 2026-07-08 09:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap_analysis', '0002_developmentplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeskill',
            name='rating_status',
            field=models.CharField(choices=[('none', 'No Self-Rating'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('overridden', 'Overridden')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='employeeskill',
            name='self_rated_level',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='employeeskill',
            name='self_rated_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
